namespace PTClient.Generator
{
    internal static class Context
    {
        internal const string INFORMATION = @"Hi,this app is made for generate Telegram.Td functions.
Functions generated by this app only useful in Telegram.Td.PTClient
For use this app you can use the following instructions
-Enter 'Generate' command and put output directory folder
-Enter 'Exit' for close this app
-Enter 'About' for show this text

Current Telegram.Td version : 1.7
New updates are coming soon on Github
";
    }
}
